config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :drivers
  resources :rentals
  resources :cars
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'drivers#index'
end

app/models/rental.rb
class Rental < ApplicationRecord


	attr_reader :car, :days_rented

	def initialize(car, days_rented)
		@car = car
		@days_rented = days_rented

		if !(@days_rented > 0)
	raise 'Error: days_rented invalid'
	end

# Moved method from driver to rental object, defined as rental_total
	def rental_total
	  result = 0
  	case rental.car.style
  	when Car::SUV
  	  result += rental.days_rented * 30
  	when Car::HATCHBACK
  	  result += 15
  	  if rental.days_rented > 3
  		  result += (rental.days_rented - 3) * 15
  	  end
  	when Car::SALOON
  	  result += 20
  	  if rental.days_rented > 2
  	     result += (rental.days_rented - 2) * 15
  	  end
  	  result
  	end


  	def added_bonus
  		bonus_points = bonus_points + 1
		if rental.car.style == Car::SUV && rental.days_rented > 1
			bonus_points = bonus_points + 1
		end
  end

end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: [:show, :edit, :update, :destroy]

  # GET /rentals
  # GET /rentals.json
  def index
    @rentals = Rental.all
  end

  # GET /rentals/1
  # GET /rentals/1.json
  def show
  end

  # GET /rentals/new
  def new
    @rental = Rental.new
  end

  # GET /rentals/1/edit
  def edit
  end

  # POST /rentals
  # POST /rentals.json
  def create
    @rental = Rental.new(rental_params)

    respond_to do |format|
      if @rental.save
        format.html { redirect_to @rental, notice: 'Rental was successfully created.' }
        format.json { render :show, status: :created, location: @rental }
      else
        format.html { render :new }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rentals/1
  # PATCH/PUT /rentals/1.json
  def update
    respond_to do |format|
      if @rental.update(rental_params)
        format.html { redirect_to @rental, notice: 'Rental was successfully updated.' }
        format.json { render :show, status: :ok, location: @rental }
      else
        format.html { render :edit }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rentals/1
  # DELETE /rentals/1.json
  def destroy
    @rental.destroy
    respond_to do |format|
      format.html { redirect_to rentals_url, notice: 'Rental was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental
      @rental = Rental.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rental_params
      params.require(:rental).permit(:car, :days_rented)
    end
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/rentals/_form.html.erb
<%= form_with(model: rental, local: true) do |form| %>
  <% if rental.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rental.errors.count, "error") %> prohibited this rental from being saved:</h2>

      <ul>
        <% rental.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :car %>
    <%= form.text_field :car %>
  </div>

  <div class="field">
    <%= form.label :days_rented %>
    <%= form.number_field :days_rented %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rentals/edit.html.erb
<h1>Editing Rental</h1>

<%= render 'form', rental: @rental %>

<%= link_to 'Show', @rental %> |
<%= link_to 'Back', rentals_path %>

app/views/rentals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rentals</h1>

<table>
  <thead>
    <tr>
      <th>Car</th>
      <th>Days rented</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rentals.each do |rental| %>
      <tr>
        <td><%= rental.car %></td>
        <td><%= rental.days_rented %></td>
        <td><%= link_to 'Show', rental %></td>
        <td><%= link_to 'Edit', edit_rental_path(rental) %></td>
        <td><%= link_to 'Destroy', rental, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rental', new_rental_path %>

app/views/rentals/new.html.erb
<h1>New Rental</h1>

<%= render 'form', rental: @rental %>

<%= link_to 'Back', rentals_path %>

app/views/rentals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Car:</strong>
  <%= @rental.car %>
</p>

<p>
  <strong>Days rented:</strong>
  <%= @rental.days_rented %>
</p>

<%= link_to 'Edit', edit_rental_path(@rental) %> |
<%= link_to 'Back', rentals_path %>