config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :drivers
  resources :rentals
  resources :cars
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'drivers#index'
end

app/models/driver.rb
class Driver < ApplicationRecord

attr_reader :title

  def initialize(name)
	@name = name
	@rentals = []
  end

  def add_rental(rentals)
	@rentals << rental
  end

  #test moved method in rental works, defined rental_total in rental
  def amount_for(rental)
  	rental.rental_total
  end


  def statement
  	total, bonus_points = 0,0
  	result = 'Car rental for #{@name.to_s}\n'
  	@rentals.each do |rental|
  		#adding bonus points to amount
  	  if rental.rental_total < 0
		bonus_points -= 10
	  end
	  bonus_points = bonus_points + 1
	  if rental.car.style == Car::SUV && rental.days_rented > 1
		  bonus_points = bonus_points + 1
	  end

		#getting results

	  result += rental.car.title.to_s + "," + rental.rental_total.to_s + "\n"
	  total += rental.rental_total
	end

	result += "Amount owed is " + "#{total.to_s}" + "\n"
	result += "Earned bonus points: " + bonus_points.to_s
	result
  end

 


  #Implement new method, split original code base
  #Simplified for coder, made more intuitive the variable name "amount_for" to "result", r to "rental" object   



 
=begin ORIGINAL
  def statement
   total = 0
   bonus points = 0
   result = 'Car rental for #{@name.to_s}\n'
    for r in @rentals
	  this_amount = 0
	  case r.car.style
	  when Car::SUV
		  this_amount += r.days_rented * 30
	  when Car::HATCHBACK 
		  this_amount += 15
	  if r.days_rented > 3
		  this_amount += (r.days_rented - 3) * 15
	  end
	  when Car::SALOON
		  this_amount += 20
	  if r.days_rented > 2
		  this_amount += (r.days_rented - 2) * 15
	  end
	  else
	end 

		if this_amount < 0
			bonus_points -= 10
		end

		bonus_points = bonus_points + 1
		if r.car.style == Car::SUV && r.days_rented > 1
			bonus_points = bonus_points + 1
		end

		result += r.car.title.to_s + "," + this_amount.to_s + "\n"
		total += this_amount
	end

	result += "Amount owed is " + "#{total.to_s}" + "\n"
	result +="Earned bonus points: " + bonus_points.to_s
	result
end

=end

# display statement in JSON format

  def json_statement
  	return {:result => result}
  end


 
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /drivers
  # GET /drivers.json
  def index
    @drivers = Driver.all
  end

  # GET /drivers/1
  # GET /drivers/1.json
  def show
  end

  # GET /drivers/new
  def new
    @driver = Driver.new
  end

  # GET /drivers/1/edit
  def edit
  end

  # POST /drivers
  # POST /drivers.json
  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: 'Driver was successfully created.' }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drivers/1
  # PATCH/PUT /drivers/1.json
  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.json
  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url, notice: 'Driver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def driver_params
      params.require(:driver).permit(:name, :rentals)
    end
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/_form.html.erb
<%= form_with(model: driver, local: true) do |form| %>
  <% if driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
        <% driver.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :rentals %>
    <%= form.number_field :rentals %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/drivers/edit.html.erb
<h1>Editing Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Show', @driver %> |
<%= link_to 'Back', drivers_path %>

app/views/drivers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Drivers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rentals</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drivers.each do |driver| %>
      <tr>
        <td><%= driver.name %></td>
        <td><%= driver.rentals %></td>
        <td><%= link_to 'Show', driver %></td>
        <td><%= link_to 'Edit', edit_driver_path(driver) %></td>
        <td><%= link_to 'Destroy', driver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Driver', new_driver_path %>

app/views/drivers/new.html.erb
<h1>New Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Back', drivers_path %>

app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @driver.name %>
</p>

<p>
  <strong>Rentals:</strong>
  <%= @driver.rentals %>
</p>

<%= link_to 'Edit', edit_driver_path(@driver) %> |
<%= link_to 'Back', drivers_path %>